// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mann_whitney_probs_int
List mann_whitney_probs_int(const IntegerVector m, const IntegerVector n);
RcppExport SEXP _DiscreteTests_mann_whitney_probs_int(SEXP mSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mann_whitney_probs_int(m, n));
    return rcpp_result_gen;
END_RCPP
}
// sign_rank_probs_int
List sign_rank_probs_int(const NumericVector n);
RcppExport SEXP _DiscreteTests_sign_rank_probs_int(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(sign_rank_probs_int(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DiscreteTests_mann_whitney_probs_int", (DL_FUNC) &_DiscreteTests_mann_whitney_probs_int, 2},
    {"_DiscreteTests_sign_rank_probs_int", (DL_FUNC) &_DiscreteTests_sign_rank_probs_int, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_DiscreteTests(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
